# Generated by Django 2.1.1 on 2018-10-20 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictModel',
            fields=[
                ('district_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('district_title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'district_table',
            },
        ),
        migrations.CreateModel(
            name='ProvinceModel',
            fields=[
                ('province_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('province_title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'province_table',
            },
        ),
        migrations.CreateModel(
            name='StreetModel',
            fields=[
                ('street_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('street_title', models.CharField(max_length=50)),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.DistrictModel')),
            ],
            options={
                'db_table': 'street_table',
            },
        ),
        migrations.CreateModel(
            name='TownModel',
            fields=[
                ('town_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('town_title', models.CharField(max_length=50)),
                ('province_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ProvinceModel')),
            ],
            options={
                'db_table': 'town_table',
            },
        ),
        migrations.AddField(
            model_name='districtmodel',
            name='town_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TownModel'),
        ),
    ]
