# Generated by Django 2.1.1 on 2018-10-21 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181021_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='districtmodel',
            name='town_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TownModel'),
        ),
    ]
