# Generated by Django 2.1.1 on 2018-10-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181021_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('service_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('service_title', models.CharField(max_length=50)),
                ('service_detail', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'service_table',
            },
        ),
    ]
