# Generated by Django 2.1.3 on 2018-11-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181028_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemodel',
            name='service_detail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
