# Generated by Django 2.1.1 on 2018-10-21 14:51

from django.db import migrations, models
#import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentHourModel',
            fields=[
                ('app_hour_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=4)),
                ('month', models.CharField(max_length=2)),
                ('day', models.CharField(max_length=2)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'db_table': 'appointment_hour_table',
            },
        ),
        migrations.CreateModel(
            name='CorpLocModel',
            fields=[
                ('corp_loc_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'corp_loc_table',
            },
        ),
        migrations.CreateModel(
            name='CorporationModel',
            fields=[
                ('corp_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('corp_name', models.CharField(max_length=50)),
                ('corp_category', models.CharField(max_length=50)),
                ('corp_app_freq', models.CharField(max_length=5)),
                ('corp_rating', models.CharField(max_length=5)),
                ('corp_details', models.CharField(max_length=200)),
                ('corp_email', models.EmailField(max_length=254)),
#                ('corp_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('corp_pass', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'corporation_table',
            },
        ),
    ]
