# Generated by Django 2.1.1 on 2018-10-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0004_auto_20181028_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporationmodel',
            name='corp_pass',
        ),
    ]
