# Generated by Django 2.1.3 on 2018-11-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0005_remove_corporationmodel_corp_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporationmodel',
            name='corp_category',
            field=models.CharField(choices=[('Hairdresser', '1'), ('Beauty Salon', '2'), ('Football Pitch', '3'), ('Nutritionist', '4'), ('Psychologist', '5'), ('Other', '6')], max_length=50),
        ),
    ]
