# Generated by Django 2.1.3 on 2018-11-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0006_auto_20181104_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporationmodel',
            name='corp_details',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='corpservicemodel',
            name='details',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ratingmodel',
            name='details',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
