# Generated by Django 2.0.8 on 2018-11-05 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0007_auto_20181106_0004'),
        ('corporation', '0007_auto_20181104_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporationmodel',
            name='corp_rep',
        ),
        migrations.AddField(
            model_name='corplocmodel',
            name='corp_rep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='individual.IndividualModel'),
        ),
    ]
