# Generated by Django 2.0.8 on 2018-11-05 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0008_auto_20181106_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corplocmodel',
            name='corp_rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individual.IndividualModel'),
        ),
    ]
