# Generated by Django 2.0.8 on 2018-11-07 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0009_auto_20181106_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmenthourmodel',
            name='day',
        ),
        migrations.RemoveField(
            model_name='appointmenthourmodel',
            name='month',
        ),
        migrations.RemoveField(
            model_name='appointmenthourmodel',
            name='year',
        ),
        migrations.AddField(
            model_name='appointmenthourmodel',
            name='date',
            field=models.DateField(default=datetime.date(2018, 11, 7)),
        ),
    ]
