# Generated by Django 2.0.8 on 2018-11-07 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0007_auto_20181106_0004'),
        ('corporation', '0010_auto_20181107_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corplocmodel',
            name='corp_rep',
        ),
        migrations.AddField(
            model_name='corporationmodel',
            name='corp_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='individual.IndividualModel'),
        ),
        migrations.AlterField(
            model_name='appointmenthourmodel',
            name='date',
            field=models.DateField(),
        ),
    ]
