# Generated by Django 2.0.8 on 2018-11-08 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0012_auto_20181107_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedHourModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('corp_loc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporation.CorpLocModel')),
            ],
            options={
                'db_table': 'reserved_hour_table',
            },
        ),
    ]
