# Generated by Django 2.0.8 on 2018-11-17 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0013_reservedhourmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingmodel',
            name='corp_loc_id',
        ),
        migrations.RemoveField(
            model_name='ratingmodel',
            name='ind_id',
        ),
        migrations.DeleteModel(
            name='RatingModel',
        ),
    ]
