# Generated by Django 2.1.3 on 2018-11-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0015_corporationmodel_corp_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporationmodel',
            name='corp_category',
            field=models.CharField(choices=[('1', 'Hairdresser'), ('2', 'Beauty Salon'), ('3', 'Football Pitch'), ('4', 'Nutritionist'), ('5', 'Psychologist'), ('6', 'Other')], max_length=50),
        ),
    ]
