# Generated by Django 2.1.3 on 2018-12-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0016_auto_20181125_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpservicemodel',
            name='corp_loc_id',
        ),
        migrations.AddField(
            model_name='corpservicemodel',
            name='corporation_id',
            field=models.CharField(default='asd', max_length=20),
            preserve_default=False,
        ),
    ]
