# Generated by Django 2.1.3 on 2018-12-09 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0017_auto_20181209_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpservicemodel',
            name='corporation_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='corporation.CorporationModel'),
        ),
    ]
