# Generated by Django 2.1.1 on 2018-10-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentModel',
            fields=[
                ('appointment_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('corp_loc_id', models.CharField(max_length=20)),
                ('person_id', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
                ('month', models.CharField(max_length=2)),
                ('day', models.CharField(max_length=2)),
                ('hour', models.TimeField()),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
    ]
