# Generated by Django 2.1.1 on 2018-10-27 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='corp_loc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporation.CorporationModel'),
        ),
        migrations.AlterField(
            model_name='appointmentmodel',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='individual.IndividualModel'),
        ),
    ]
