# Generated by Django 2.1.3 on 2018-11-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20181028_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentmodel',
            name='detail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
