# Generated by Django 2.0.8 on 2018-11-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20181108_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentmodel',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
