# Generated by Django 2.0.8 on 2018-11-08 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0012_auto_20181107_1238'),
        ('records', '0006_auto_20181108_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='corp_loc_id',
        ),
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='hour',
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='app_hour_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='corporation.AppointmentHourModel'),
            preserve_default=False,
        ),
    ]
