# Generated by Django 2.0.8 on 2018-11-08 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0013_reservedhourmodel'),
        ('records', '0007_auto_20181108_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentmodel',
            name='app_hour_id',
        ),
        migrations.AddField(
            model_name='appointmentmodel',
            name='res_hour_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='corporation.ReservedHourModel'),
            preserve_default=False,
        ),
    ]
