# Generated by Django 2.0.8 on 2018-11-17 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0014_auto_20181117_1348'),
        ('individual', '0007_auto_20181106_0004'),
        ('records', '0009_appointmentmodel_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=5)),
                ('details', models.CharField(blank=True, max_length=200, null=True)),
                ('corp_loc_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corporation.CorpLocModel')),
                ('ind_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='individual.IndividualModel')),
            ],
            options={
                'db_table': 'rating_table',
            },
        ),
    ]
