# Generated by Django 2.1.3 on 2018-11-29 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0016_auto_20181125_1636'),
        ('records', '0010_ratingmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingmodel',
            name='corp_loc_id',
        ),
        migrations.AddField(
            model_name='ratingmodel',
            name='corp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corporation.CorporationModel'),
        ),
    ]
