# Generated by Django 2.1.3 on 2018-11-25 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporation', '0016_auto_20181125_1636'),
        ('user', '0003_auto_20181107_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='corp_loc_id',
        ),
        migrations.AddField(
            model_name='user',
            name='corporation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corporation.CorporationModel'),
        ),
    ]
