# Generated by Django 2.1.1 on 2018-10-21 14:51

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0003_auto_20181021_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualModel',
            fields=[
                ('ind_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ind_name', models.CharField(max_length=50)),
                ('ind_lastname', models.CharField(max_length=50)),
                ('ind_email', models.EmailField(max_length=254)),
                ('ind_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('ind_rating', models.CharField(max_length=5)),
                ('ind_password', models.CharField(max_length=20)),
                ('ind_detail', models.CharField(max_length=200)),
                ('ind_no', models.CharField(max_length=11)),
                ('ind_bday', models.DateField()),
                ('ind_statu', models.CharField(max_length=100)),
                ('ind_gender', models.NullBooleanField()),
                ('ind_loc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.StreetModel')),
            ],
            options={
                'db_table': 'individual_table',
            },
        ),
    ]
