# Generated by Django 2.1.1 on 2018-10-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualmodel',
            name='ind_id',
        ),
        migrations.AddField(
            model_name='individualmodel',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
