# Generated by Django 2.1.1 on 2018-10-28 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0003_remove_individualmodel_ind_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualmodel',
            name='ind_loc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.StreetModel'),
        ),
        migrations.AlterField(
            model_name='individualmodel',
            name='ind_rating',
            field=models.CharField(default=0.0, max_length=5),
        ),
    ]
