# Generated by Django 2.1.3 on 2018-11-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0004_auto_20181028_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualmodel',
            name='ind_detail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
