# Generated by Django 2.1.3 on 2018-11-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0005_auto_20181104_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualmodel',
            name='ind_statu',
            field=models.CharField(choices=[('Married', '1'), ('Single', '2')], max_length=100),
        ),
    ]
