# Generated by Django 2.0.8 on 2018-11-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0006_auto_20181104_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualmodel',
            name='ind_gender',
            field=models.CharField(choices=[('Male', '1'), ('Female', '2')], max_length=100, null=True),
        ),
    ]
