# Generated by Django 2.1.3 on 2018-11-25 12:55

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0007_auto_20181106_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualmodel',
            name='ind_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+905554443322', max_length=128),
        ),
    ]
