# Generated by Django 2.1.3 on 2018-11-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual', '0008_auto_20181125_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualmodel',
            name='ind_gender',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='individualmodel',
            name='ind_statu',
            field=models.CharField(choices=[('1', 'Married'), ('2', 'Single')], max_length=100),
        ),
    ]
